// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuoteBBOData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TigerOpenAPI.Quote.Pb {

  /// <summary>Holder for reflection information generated from QuoteBBOData.proto</summary>
  public static partial class QuoteBBODataReflection {

    #region Descriptor
    /// <summary>File descriptor for QuoteBBOData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuoteBBODataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJRdW90ZUJCT0RhdGEucHJvdG8SNGNvbS50aWdlcmJyb2tlcnMuc3RvY2su",
            "b3BlbmFwaS5jbGllbnQuc29ja2V0LmRhdGEucGIaElNvY2tldENvbW1vbi5w",
            "cm90byKrAgoMUXVvdGVCQk9EYXRhEg4KBnN5bWJvbBgBIAEoCRJaCgR0eXBl",
            "GAIgASgOMkwuY29tLnRpZ2VyYnJva2Vycy5zdG9jay5vcGVuYXBpLmNsaWVu",
            "dC5zb2NrZXQuZGF0YS5wYi5Tb2NrZXRDb21tb24uUXVvdGVUeXBlEhEKCXRp",
            "bWVzdGFtcBgDIAEoBBIQCghhc2tQcmljZRgRIAEoARIPCgdhc2tTaXplGBIg",
            "ASgSEhkKDGFza1RpbWVzdGFtcBgTIAEoBEgAiAEBEhAKCGJpZFByaWNlGBQg",
            "ASgBEg8KB2JpZFNpemUYFSABKBISGQoMYmlkVGltZXN0YW1wGBYgASgESAGI",
            "AQFCDwoNX2Fza1RpbWVzdGFtcEIPCg1fYmlkVGltZXN0YW1wQhiqAhVUaWdl",
            "ck9wZW5BUEkuUXVvdGUuUGJQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TigerOpenAPI.Quote.Pb.SocketCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TigerOpenAPI.Quote.Pb.QuoteBBOData), global::TigerOpenAPI.Quote.Pb.QuoteBBOData.Parser, new[]{ "Symbol", "Type", "Timestamp", "AskPrice", "AskSize", "AskTimestamp", "BidPrice", "BidSize", "BidTimestamp" }, new[]{ "AskTimestamp", "BidTimestamp" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class QuoteBBOData : pb::IMessage<QuoteBBOData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QuoteBBOData> _parser = new pb::MessageParser<QuoteBBOData>(() => new QuoteBBOData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QuoteBBOData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TigerOpenAPI.Quote.Pb.QuoteBBODataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QuoteBBOData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QuoteBBOData(QuoteBBOData other) : this() {
      _hasBits0 = other._hasBits0;
      symbol_ = other.symbol_;
      type_ = other.type_;
      timestamp_ = other.timestamp_;
      askPrice_ = other.askPrice_;
      askSize_ = other.askSize_;
      askTimestamp_ = other.askTimestamp_;
      bidPrice_ = other.bidPrice_;
      bidSize_ = other.bidSize_;
      bidTimestamp_ = other.bidTimestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QuoteBBOData Clone() {
      return new QuoteBBOData(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType type_ = global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType.None;
    /// <summary>
    /// BBO
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "askPrice" field.</summary>
    public const int AskPriceFieldNumber = 17;
    private double askPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double AskPrice {
      get { return askPrice_; }
      set {
        askPrice_ = value;
      }
    }

    /// <summary>Field number for the "askSize" field.</summary>
    public const int AskSizeFieldNumber = 18;
    private long askSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AskSize {
      get { return askSize_; }
      set {
        askSize_ = value;
      }
    }

    /// <summary>Field number for the "askTimestamp" field.</summary>
    public const int AskTimestampFieldNumber = 19;
    private ulong askTimestamp_;
    /// <summary>
    /// Pre/Post-Mkt data not support
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong AskTimestamp {
      get { if ((_hasBits0 & 1) != 0) { return askTimestamp_; } else { return 0UL; } }
      set {
        _hasBits0 |= 1;
        askTimestamp_ = value;
      }
    }
    /// <summary>Gets whether the "askTimestamp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAskTimestamp {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "askTimestamp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAskTimestamp() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "bidPrice" field.</summary>
    public const int BidPriceFieldNumber = 20;
    private double bidPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double BidPrice {
      get { return bidPrice_; }
      set {
        bidPrice_ = value;
      }
    }

    /// <summary>Field number for the "bidSize" field.</summary>
    public const int BidSizeFieldNumber = 21;
    private long bidSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BidSize {
      get { return bidSize_; }
      set {
        bidSize_ = value;
      }
    }

    /// <summary>Field number for the "bidTimestamp" field.</summary>
    public const int BidTimestampFieldNumber = 22;
    private ulong bidTimestamp_;
    /// <summary>
    /// Pre/Post-Mkt data not support
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BidTimestamp {
      get { if ((_hasBits0 & 2) != 0) { return bidTimestamp_; } else { return 0UL; } }
      set {
        _hasBits0 |= 2;
        bidTimestamp_ = value;
      }
    }
    /// <summary>Gets whether the "bidTimestamp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBidTimestamp {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "bidTimestamp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBidTimestamp() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QuoteBBOData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QuoteBBOData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (Type != other.Type) return false;
      if (Timestamp != other.Timestamp) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(AskPrice, other.AskPrice)) return false;
      if (AskSize != other.AskSize) return false;
      if (AskTimestamp != other.AskTimestamp) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(BidPrice, other.BidPrice)) return false;
      if (BidSize != other.BidSize) return false;
      if (BidTimestamp != other.BidTimestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (Type != global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType.None) hash ^= Type.GetHashCode();
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (AskPrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(AskPrice);
      if (AskSize != 0L) hash ^= AskSize.GetHashCode();
      if (HasAskTimestamp) hash ^= AskTimestamp.GetHashCode();
      if (BidPrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(BidPrice);
      if (BidSize != 0L) hash ^= BidSize.GetHashCode();
      if (HasBidTimestamp) hash ^= BidTimestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (Type != global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Timestamp);
      }
      if (AskPrice != 0D) {
        output.WriteRawTag(137, 1);
        output.WriteDouble(AskPrice);
      }
      if (AskSize != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteSInt64(AskSize);
      }
      if (HasAskTimestamp) {
        output.WriteRawTag(152, 1);
        output.WriteUInt64(AskTimestamp);
      }
      if (BidPrice != 0D) {
        output.WriteRawTag(161, 1);
        output.WriteDouble(BidPrice);
      }
      if (BidSize != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteSInt64(BidSize);
      }
      if (HasBidTimestamp) {
        output.WriteRawTag(176, 1);
        output.WriteUInt64(BidTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (Type != global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Timestamp);
      }
      if (AskPrice != 0D) {
        output.WriteRawTag(137, 1);
        output.WriteDouble(AskPrice);
      }
      if (AskSize != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteSInt64(AskSize);
      }
      if (HasAskTimestamp) {
        output.WriteRawTag(152, 1);
        output.WriteUInt64(AskTimestamp);
      }
      if (BidPrice != 0D) {
        output.WriteRawTag(161, 1);
        output.WriteDouble(BidPrice);
      }
      if (BidSize != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteSInt64(BidSize);
      }
      if (HasBidTimestamp) {
        output.WriteRawTag(176, 1);
        output.WriteUInt64(BidTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (Type != global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (AskPrice != 0D) {
        size += 2 + 8;
      }
      if (AskSize != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeSInt64Size(AskSize);
      }
      if (HasAskTimestamp) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(AskTimestamp);
      }
      if (BidPrice != 0D) {
        size += 2 + 8;
      }
      if (BidSize != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeSInt64Size(BidSize);
      }
      if (HasBidTimestamp) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(BidTimestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QuoteBBOData other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.Type != global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType.None) {
        Type = other.Type;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      if (other.AskPrice != 0D) {
        AskPrice = other.AskPrice;
      }
      if (other.AskSize != 0L) {
        AskSize = other.AskSize;
      }
      if (other.HasAskTimestamp) {
        AskTimestamp = other.AskTimestamp;
      }
      if (other.BidPrice != 0D) {
        BidPrice = other.BidPrice;
      }
      if (other.BidSize != 0L) {
        BidSize = other.BidSize;
      }
      if (other.HasBidTimestamp) {
        BidTimestamp = other.BidTimestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType) input.ReadEnum();
            break;
          }
          case 24: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 137: {
            AskPrice = input.ReadDouble();
            break;
          }
          case 144: {
            AskSize = input.ReadSInt64();
            break;
          }
          case 152: {
            AskTimestamp = input.ReadUInt64();
            break;
          }
          case 161: {
            BidPrice = input.ReadDouble();
            break;
          }
          case 168: {
            BidSize = input.ReadSInt64();
            break;
          }
          case 176: {
            BidTimestamp = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::TigerOpenAPI.Quote.Pb.SocketCommon.Types.QuoteType) input.ReadEnum();
            break;
          }
          case 24: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 137: {
            AskPrice = input.ReadDouble();
            break;
          }
          case 144: {
            AskSize = input.ReadSInt64();
            break;
          }
          case 152: {
            AskTimestamp = input.ReadUInt64();
            break;
          }
          case 161: {
            BidPrice = input.ReadDouble();
            break;
          }
          case 168: {
            BidSize = input.ReadSInt64();
            break;
          }
          case 176: {
            BidTimestamp = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
